char *alltext[326] =
{
	"   Men have been disappearing from the village!  I have seen a strange glowing light in the woods right before some of the men vanished. That's all I know! |",
	"   Human, your life is forfeit and your soul is mine! I shall enjoy ripping you apart for eternity! |",
	"   I don't know what else to tell you! Maybe you should go and look into the strange lights I've seen out in the woods. |",
	"   Demons that look like beautiful women! That's horrible! You must stop this madness, or we may all perish! |",
	"   YOUU...HUMANN! I...WWILLL...REEEWARD...YOUU...VVVERY...WELLLL...IFFF...YOUU...HELLP...MEEE...ESSCAAPE...JUSSST...REEAD...TTHAT...BOOOK... |",
	NULL,
	"   I bring word from the Church.  Through dark means, the Bishop Lazarus was corrupted. His betrayal has allowed Diablo to gain a foothold in our world, and now he works in futherance of Diablo's schemes. We have divined his current location as being sixteen levels under the church. He must be stopped, and his soul put to rest. |",
	NULL,
	"   Interloper! You dare to interfere with our destiny! You shall suffer a slow, painful death! |",
	"   You are too late! Now you will feel the wrath of hell! |",
	"   Why do you delay?! Lazarus' actions doom us all. Hurry! |",
	"   It is a weight off of my heart. Rest in peace Bishop Lazarus. I believe you are worthy of one of the Church's holy weapons. The Church appoints you charge of the mace Lightforge. Use it well, and God speed! |",
	NULL,
	"   This is terrible, I don't know when we will get another chance. Well it was worth the try. Good luck my son, I feel that you will face more horrors, be strong and you will succeed. |",
	NULL,
	"   I don't know if I should be telling you this, but I overheard the new priest talking yesterday. He was having a quiet argument with someone I didn't recognize.  The stranger said that you should not be told about something he called Azurewrath, or the Angel named Izual! There was something about a key in a barrel. I'm sorry but that is all I heard, I hope it helps. |",
	"   Another mortal seeks his death... |",
	"   Maybe it wasn't a key in a barrel, but rather that a barrel was the key. |",
	"   Azurewrath is a magical sword! And Izual was a Fallen Angel! I hope you didn't get hurt, and I'm glad I was able to help you! Good luck, I know you'll do your best to save our land from the darkness. |",
	NULL,
	"   The weapons you got from that Hellish place are far better than any I can make.  How can there be so many magical weapons in that place!. When I was a boy, my father told me of a magic anvil.  Any weapon made with this anvil would also be magical. He called it the Anvil of Fury. I don't know where it would be, but the magic weapons would need a really hot tempering. |",
	NULL,
	"   The Anvil of Fury would allow me to make magical weapons for you! Magic weapons would need a really hot forge to temper.  I hope you can find it. Good Luck! |",
	NULL,
	"   Wow! You found it... oh... that looks really heavy! You can put it down right over there! Perfect! The first weapon I make with it is yours my friend! |",
	"   Hey, yyou..friend...thhank you...thanks...the Angel island where Angels watch...watched...you neeed...the...chchoose the rright rrock...and...shield you eyes...shield everything...you...... |",
	NULL,
	"   I represent the Church on this matter. We believe that through the Cathedral you are entering Hell itself. This provides a unique opportunity...Many years ago, a demonic beast rose from the depths and razed entire villages. We finally vanquished him, only to have him return twice now, to repeat this foul cycle. Perhaps if he is destroyed below, in his own plane, he will forever be defeated... If Fleshdoom possesses a blade composed of the blackest metal, do not use it! Bring the tainted weapon to me, so I can dispose of it. I believe he resides in the deepest levels under the cathedral. |",
	NULL,
	"   I wish you luck in hunting Fleshdoom, his evil goes beyond words. Remember, the accursed black sword he wields should not be used by mortal man. Bring it back to me, only my powers can destroy it. |",
	"   Good..but we must also destroy the sword, for this evil to end... |",
	"   You did it! Lord be praised! Please, let me now destroy that evil weapon of Hell!...Oh, no...what's happening...it isn't working...Quickly! Our only chance now is to cast this weapon into the Forge of Hell, from whence it came! Try further still...into the depths...Oh, my...god... |",
	"   YOU HAVE TAKEN YOUR LAST BREATH HUMAN! MY BLADE SHALL FEED ON YOUR FLESH, AND I SHALL TASTE YOUR PAIN AS YOU DIE! |",
	"   Please! Don't kill me...I was once human...I have been looking for a cure to this curse, but it is locked away far beyond my reach...If you help me, I will help you...Look for a Golden Elixor. |",
	NULL,
	"   No elixor? I fear that I am doomed for eternity...Please keep trying... |",
	"   I owe you my life. Take this helm! It was my prison here in this realm, but now maybe you can use it to avenge this evil! |",
	"   Damn...Where is that map...Dad said it was between the rock and the tree...before the bridge...It should be right h- OH! Hi...uh...didn’t see ya there...uh... |",
	"   What have we here? A map... ...hmmm...This bodes of great ill...You must work quickly now! Diablo readies his armies for impending attack. Take back this map and check it often. When the two stars align, Diablo will complete the final ritual necessary to open a full gate into our world. Our only hope is that you stop him before this confluence. Go now! And Hurry! |",
	"   We have very little time...I sense Diablo's power building... |",
	"   {I can brew better potions if you can find this for me:} |",
	"   {I can brew better potions if you can find this for me:} |",
	"   {Great! Here's a sample.} |",
	"   {I could write a book of magic if I could study these scrolls:} |",
	"   {I could write a book of magic if I could study these scrolls:} |",
	"   {Thank you, I will teach you what I learn.} |",
	"   {Great power can be found in iron figurines below the church. I can work wonders with these:} |",
	"   {Great power can be found in iron figurines below the church. I can work wonders with these:} |",
	"   {This is amazing! Now I need a specific staff to invoke its power:} |",
	"   {I need a staff to invoke the power of the figurines.} |",
	"   {That's just what we need! I hope you like the results.} |",
	NULL,
	"   {The king's army is in need of supplies, these items will fetch a special price.} |",
	"   {The king's army is in need of supplies, these items will fetch a special price.} |",
	"   {Excellent! Here is your reward.} |",
	NULL,
	"   {I've got an idea I want to test. Find me this weapon and I think I can make it better:} |",
	"   {Find me this weapon and I think I can make it better:} |",
	"   {Let me just...It works! Take this back and give it a try!.} |",
	"   {I'm working on a method for toughening armor. I can try it if you bring me this:} |",
	"   {I'm working on a method for toughening armor. I can try it if you bring me this:} |",
	"   {Good find! See if this works any better for you.} |",
	NULL,
	"   {If you come across enchanted equipment, I can try to use its methods on my own creations. Here is what I seek:} |",
	"   {Here is what I seek:} |",
	"   {Thank you! This will take some study...} |",
	"   {Keep your eyes open for an iron figurine. I have special knowledge about these:} |",
	"   {Keep your eyes open for these:} |",
	NULL,
	"   {This is amazing! Now I need one of these, and I will make it gleam with power!} |",
	"   {Now I need one of these, and I will make it gleam with power!} |",
	"   {That looks just fine! I believe you will like this alot.} |",
	"   {A traveller passed through recently wielding a unique weapon. He believed that killing a certain monster with it would invoke its true power. As he has not returned, I fear he is dead.} |",
	NULL,
	"   {Have you seen the traveller with the enchanted weapon? I fear he is dead.} |",
	"   {That is the traveller's weapon. He was hunting this monster:} |",
	NULL,
	"   {One of my regular patrons seeks vengeance for her slain brother. She will reward you if you bring me evidence that you have killed this monster:} |",
	"   {For proof of vengeance fullfilled I need this:} |",
	"   {Ahh! I hope this put's her mind at ease...Here is your reward.} |",
	"   {A nearby home was ransacked by a group of foul beasts. They killed the owner and took a chest full of valuable belongings. You will need the key first, so look for these creatures:} |",
	"   {These creatures hold the key to a valuable chest:} |",
	"   {I see you have the key, now find the chest that it opens.} |",
	"   {You'd be my hero, if you slayed this monster for me!} |",
	"   {Won't you prove your worth by besting this demon?} |",
	"   {My! Aren't you brave!} |",
	"   {It is said that, on this day, if you leave a token in the cemetary, tomorrow it will be altered. Try one of these:} |",
	"   {It is said that, on this day, if you leave a token in the cemetary, tomorrow it will be altered. Try one of these:} |",
	"   {I had a dream that you punched a demon and it exploded into fabulous treasure. I think the beast had this name:} |",
	"   {I had a dream that you punched a demon and it exploded into fabulous treasure. I think the beast had this name:} |",
	"   {Hey! Its my best customer! My partner had an accident and I need some help refilling my inventory. I'll trade you my best item if you can bring me these:} |",
	"   {I'll trade you my best item if you can bring me these:} |",
	NULL,
	"   {Thanks! This should tide me over 'till I find a new partner. Here's your half of the bargain:} |",
	"   {I've got something special today. I'm not exactly sure what it is, but I can tell that it's great...So, I'm gonna offer you a bargain: 1000 gold takes it. No questions, no returns.} |",
	NULL,
	"   {I've acquired a certain rare tome. This book requires a crystal eyepiece to read, however, and I don't have it. The book is useless to me. I will give it to you if you give me these things:} |",
	"   {Give me these things and I will give you a rare tome:} |",
	"   {You got it all! Here's the Tome. I hope you find the crystal eyepiece, without it you will never be able to read it.} |",
	"   {I must speak with you! While calling on a villager, I came upon a Demon! I left the door open for you. Please investigate!} |",
	"   {These creatures must be banished! I left the door open for you.} |",
	"   {The village is once again in your debt.} |",
	"   {I am in need of a certain reagents to help heal the plagues that the demons bring. If you gather these things, I shall reward you well:} |",
	"   {I am in need of a certain reagents to help heal the plagues that the demons bring. If you gather these things, I shall reward you well:} |",
	"   {You bring light to this dark and troubled time...I wish you to have this...} |",
	"   {I ask that you find a pool of clear water. Fill these containers and return. Then I will concoct a useful elixor.} |",
	"   {I ask that you find a pool of clear water. Fill these containers and return. Then I will concoct a useful elixor.} |",
	"   {Very good! Just give me a minute to mix the ingrediants... ...Ah! Here you go!.} |",
	"   {I wanna tell ya...and I know this stuff...this's's what ya might call my espesiality, so lissen' up...this here is the best...thee best...you lissen' ta me...} |",
	NULL,
	"   ...no one ever lis-HICK...lissen's to me...sumwhere...I ain't too sure...sumwhere...just unner the church...is a whole pile o' gold...gleemin' an' a shinin'.. jus waitin' fer sumone to get at it...this kinna monster hazza key...} |",
	NULL,
	"   {I know ya gots yer own eyedeas...an' I know yer not gonna baleev zis...but that weppon' yer holdin'...they jus' aint no good aginst yer tuffer beasties...} |",
	"   {If I was you...an' I aint, but if I was...I'd'a sell all a that stuff, et least mosta' it...That boy out there...that poor kid wif' no leg...no foot...he got sumpin' good...But he ain' even gonna offer it to ya, 'less you got sum gold...an' lots of it! |",

	// demo start

	"   I would like to ask your help. Years ago a corrupt king destroyed the land with necromancy.  He used his dark powers to kill all before him, then he would raise the dead to join his army of evil.  One of the king's own knights finally struck him down; now he rests in the catacombs of the cathedral.With evil upon our land once more, I fear that the Skeleton King is again at work; building an undead army.  If you slay the evil king, he can not raise his army of skeleton warriors to destroy our land.You will find the king's tomb 3 levels below.|",
	"   The Skeleton Kings undead minions still plague this land! You must kill the Dark King or the walking dead will destroy every thing! His tomb is 3 levels below.|",
	NULL,
	"   You have saved this land from a terrible evil.  With the King again resting in peace, the undead hordes will not return. Thank you.|",
	"   Please help....! I barely escaped from ....... the Butcher...! He killed .... my wife ... my children! I beg of you ...... in the name of God ......... avenge them.........|",
	"<..........> The man's body appears to be twisted in agony!|",
	"<..........> The man appears to be in peace.|",
	NULL,
	"   I have a story that I think you might be interested in. A few weeks ago a star fell from the sky.  A caravan carried a piece of the sky rock to the royal capital for the King's wizards to study.  On the road north of here, they were ambushed by evil forces eminating from the cathedral.  I looked among the refuse and carnage for the sky rock, but it was no where to be found.  If you can find it, I will try to make something out of it. If it is magical, it might be of some use to you!|",
	"   I'm still waiting for you to bring me that piece of star that fell. If it is magical, I could make something that you could use to fight the evil in our homeland.|",
	NULL,
	"   Hey! It looks like that could be it! Give me some time.....Ah! Here you go....I made a ring out of a small piece.  I hope its of some use to you. Good Luck!|",
	NULL,
	"....and so the knowledge was too great. With reluctance, the power of the awesome and destructive spell was sealed forever beyond the Chamber of Bone. A magical stairway marks the way to the Chamber. Many have tried to recover the power sealed within, but all have fallen prey to the Guardians. You have been warned.|",
	"   Here is the nova spell huhh..hhuhhhh. words....|",
	NULL,
	"Beyond the Hall of Heros awaits the catacombs. Be warned: He who would steal from the dead. Traps and more await below to deal with would be thieves.|",
	"Thank goodness you've returned! Much has changed since you lived here, my friend. All was peaceful until the dark riders came and destroyed our village. Many were cut down where they stood. Those who took up arms were slain or dragged away to become slaves - or worse. The church at the edge of town has been desecrated and is being used for dark rituals. The screams that echo in the night are inhuman, but some of our townsfolk may yet survive. Follow the path that lies between my tavern and the blacksmith shop to find the church and save who you can. Perhaps I can tell you more if we speak again. Good luck.|",
	"There is an old woman who lives across the river to the east. It is said that she knows much about magic. She may be able to help you in your quest.|",
	NULL,
	"Continue on your quest, my friend. Only the destruction of the evil that binds us can bring us peace.|",

	// demo end

	"   Everyone is sick! The demons have tunneled into our well sources and fouled our water. Find the tunnel and stop them or we will all die! |",
	"   Please, you must hurry! The demons have tunneled into our ground water and are poisoning it. |",
	"   Thank you so much! If you had not stopped them, we would all have perished! Let me express my gratitude with this magic ring. |",
	"   Here over, pssst! Chamber Butcher the from spell portal town the cast!  Saying I am what? |",
	"   No hurt! Not Kill! Keep alive, next time good bring to you! |",
	"   Something for you! Again, too! Garbud live! No hurt! |",
	"   Nothing! Could not get! Stop! Live! Live! No pain! |",
	"   Garbud big! You weak! You scared! Now you die! |",
	"   I can see what you see not. Vision milky then eyes rot. When you turn they will be gone, Whispering their hidden song. Then you see what connot be Shadows move where light should be. Out of darkness out of mind, Cast down into the Halls of the Blind.|",
	"  ...and so, locked beyond the Gateway of Blood and past the Hall of Fire. Valor awaits for the Hero of Light to awaken...THIS QUEST IS NOT WORKING YET...|",
	"   What?!...Why are you here?...All these interuptions...Here, take this and begon! Trouble me no more! NEXT TIME... |",
	NULL,
	"   Arrgghh! If you insist on disturbing my work, then I must put an end to your curiosity! |",
	"   I was calling on one of the townsmen who is very ill, when I made a bone-chilling discovery. Odd sounds...and a sick sweet smell rising from the cellar. I looked below and saw monstrous demonic worms shift and squirm. They must have tunneled up from the underlying catacombs...I emplore you! You must slay these worms! I left the man's door open for you. Its that house right in front of me... |",
	"   I fear that the worms could soon overrun the village...I think I heard them under my house. Please, seek them out through that house opposite mine... |",
	"   Once again you have saved us from the encroaching evil. We are forever in your debt. |",
	"   What do we have here?...Interesting...It looks like...Keep your eyes open for a black mushroom, it should be fairly large. |",
	"   A mushroom? Oh, yes...This will be perfect in my stew...By the way, I heard the Healer is looking for the brain of a demon... |",
	"   Why, thank you...Oh, could you bring this elixor to the witch, as long as you're going that way? |",
	"   What?! Oh, I don't need that anymore...Keep it. |",
	NULL,
	"   I don't understand why the demons stole the sign to my inn, but didn't burn it down or kill me and my family. It's so strange... don't you think? |",
	"   Hey! You that manling kill all! You get me Magic Banner or die! You no leave with life! You kill big uglies give back Magic! Past corner and door are uglys! You give you go! |",
	"   You kill uglies give banner! |",
	"   You give! Yes good! Go! Go good! We strong good! We kill all! Now magic strong! |",
	"   Oh! You didn't have to bring back my sign! But I am very glad you did. Here, take this cap, it should be of some value to you. |"
};
