void ClearCursor() // CODE_FIX: this was supposed to be in cursor.cpp
static void scrollrt_draw_cursor_back_buffer()
static void scrollrt_draw_cursor_item()
void DrawMissile(int x, int y, int sx, int sy, int a5, int a6, BOOL pre)
void DrawClippedMissile(int x, int y, int sx, int sy, int a5, int a6, BOOL pre)
static void DrawMonster(int x, int y, int mx, int my, int m, int a6, int a7)
static void DrawClippedMonster(int x, int y, int mx, int my, int m, int a6, int a7)
static void DrawPlayer(int pnum, int x, int y, int px, int py, BYTE *pCelBuff, int nCel, int nWidth, int a9, int a10)
static void DrawClippedPlayer(int pnum, int x, int y, int px, int py, BYTE *pCelBuff, int nCel, int nWidth, int a9, int a10)
void DrawDeadPlayer(int x, int y, int sx, int sy, int a5, int a6, BOOL clipped)
static void DrawObject(int x, int y, int ox, int oy, BOOL pre, int a6, int dir)
static void DrawClippedObject(int x, int y, int ox, int oy, BOOL pre, int a6, int dir)
static void scrollrt_draw_clipped_dungeon(BYTE *pBuff, int sx, int sy, int dx, int dy, int me_flag);
static void scrollrt_draw_clipped_e_flag(BYTE *pBuff, int x, int y, int a4, int a5)
static void scrollrt_draw_clipped_dungeon(BYTE *pBuff, int sx, int sy, int dx, int dy, int me_flag)
static void scrollrt_draw_lower(int x, int y, int sx, int sy, int a5, int some_flag)
static void scrollrt_draw_clipped_dungeon_2(BYTE *pBuff, int sx, int sy, int a4, int a5, int dx, int dy, int me_flag);
static void scrollrt_draw_clipped_e_flag_2(BYTE *pBuff, int x, int y, int a4, signed int a5, int sx, int sy)
static void scrollrt_draw_clipped_dungeon_2(BYTE *pBuff, int sx, int sy, int a4, int a5, int dx, int dy, int me_flag)
static void scrollrt_draw_lower_2(int x, int y, int sx, int sy, int a5, int a6, int some_flag)
static void scrollrt_draw_dungeon(BYTE *pBuff, int sx, int sy, int a4, int a5, int dx, int dy, int me_flag);
static void scrollrt_draw_e_flag(BYTE *pBuff, int x, int y, int a4, int a5, int sx, int sy)
static void scrollrt_draw_dungeon(BYTE *pBuff, int sx, int sy, int a4, int a5, int dx, int dy, int me_flag)
static void scrollrt_draw_upper(int x, int y, int sx, int sy, int a5, int a6, int some_flag)
static void DrawGame(int x, int y)
static void DrawZoom(int x, int y)
void DrawView(int StartX, int StartY)
void ClearScreenBuffer()
void ScrollView()
void EnableFrameCount()
static void DrawFPS()
static void DoBlitScreen(DWORD dwX, DWORD dwY, DWORD dwWdt, DWORD dwHgt)
static void DrawMain(int dwHgt, int draw_desc, int draw_hp, int draw_mana, int draw_sbar, int draw_btn)
void scrollrt_draw_game_screen(BOOL draw_cursor)
void DrawAndBlit()
