//appfat

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "appfat.h"
#include "diablo.h"
#include "dx.h"
#include "init.h"
#include "multi.h"

// automap

#include "../types.h"
#include "automap.h"
#include "control.h"
#include "dx.h"
#include "engine.h"
#include "gendung.h"
#include "inv.h"
#include "multi.h"
#include "player.h"
#include "quests.h"
#include "scrollrt.h"
#include "setmaps.h"

// capture

#include "../types.h"
#include "capture.h"
#include "dx.h"
#include "engine.h"
#include "scrollrt.h"

// codec

#include "../types.h"
#include "codec.h"
#include "appfat.h"
#include "sha.h"

// control

#include "../types.h"
#include "control.h"
#include "automap.h"
#include "cursor.h"
#include "diablo.h"
#include "dx.h"
#include "engine.h"
#include "error.h"
#include "gamemenu.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "lighting.h"
#include "minitext.h"
#include "missiles.h"
#include "monster.h"
#include "msg.h"
#include "msgcmd.h"
#include "multi.h"
#include "objects.h"
#include "player.h"
#include "quests.h"
#include "scrollrt.h"
#include "spells.h"
#include "stores.h"
#include "towners.h"
#include "trigs.h"

// cursor

#include "../types.h"
#include "cursor.h"
#include "control.h"
#include "diablo.h"
#include "doom.h"
#include "engine.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "missiles.h"
#include "monster.h"
#include "objects.h"
#include "player.h"
#include "quests.h"
#include "scrollrt.h"
#include "towners.h"
#include "track.h"
#include "trigs.h"

// dead

#include "../types.h"
#include "dead.h"
#include "gendung.h"
#include "lighting.h"
#include "missiles.h"
#include "monster.h"

// debug

#include "../types.h"
#include "debug.h"
#include "appfat.h"
#include "cursor.h"
#include "diablo.h"
#include "engine.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "monster.h"
#include "msg.h"
#include "player.h"
#include "quests.h"
#include "spells.h"
#include "stores.h"

// diablo

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "../DiabloUI/diabloui.h"
#include "diablo.h"
#include "appfat.h"
#include "automap.h"
#include "capture.h"
#include "control.h"
#include "cursor.h"
#include "dead.h"
#include "debug.h"
#include "doom.h"
#include "drlg_l1.h"
#include "drlg_l2.h"
#include "drlg_l3.h"
#include "drlg_l4.h"
#include "dx.h"
#include "effects.h"
#include "encrypt.h"
#include "engine.h"
#include "error.h"
#include "fault.h"
#include "gamemenu.h"
#include "gendung.h"
#include "gmenu.h"
#include "help.h"
#include "init.h"
#include "interfac.h"
#include "inv.h"
#include "items.h"
#include "lighting.h"
#include "loadsave.h"
#include "mainmenu.h"
#include "minitext.h"
#include "missiles.h"
#include "monster.h"
#include "movie.h"
#include "msg.h"
#include "msgcmd.h"
#include "multi.h"
#include "nthread.h"
#include "objects.h"
#include "palette.h"
#include "pfile.h"
#include "player.h"
#include "plrmsg.h"
#include "portal.h"
#include "quests.h"
#include "restrict.h"
#include "scrollrt.h"
#include "setmaps.h"
#include "sound.h"
#include "spells.h"
#include "stores.h"
#include "themes.h"
#include "town.h"
#include "towners.h"
#include "track.h"
#include "trigs.h"

// doom

#include "../types.h"
#include "doom.h"
#include "control.h"
#include "engine.h"

// drlgl1

#include "../types.h"
#include "drlg_l1.h"
#include "diablo.h"
#include "engine.h"
#include "gendung.h"
#include "lighting.h"
#include "monster.h"
#include "multi.h"
#include "objects.h"
#include "quests.h"

// drlgl2

#include "../types.h"
#include "drlg_l2.h"
#include "diablo.h"
#include "drlg_l1.h"
#include "engine.h"
#include "gendung.h"
#include "monster.h"
#include "multi.h"
#include "objects.h"
#include "quests.h"

// drlgl3

#include "../types.h"
#include "drlg_l3.h"
#include "drlg_l1.h"
#include "engine.h"
#include "gendung.h"
#include "lighting.h"
#include "monster.h"
#include "objects.h"
#include "quests.h"

// drlgl4

#include "../types.h"
#include "drlg_l4.h"
#include "drlg_l1.h"
#include "engine.h"
#include "gendung.h"
#include "multi.h"
#include "quests.h"

// dthread

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "dthread.h"
#include "appfat.h"
#include "engine.h"
#include "multi.h"
#include "nthread.h"

// dx

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "dx.h"
#include "appfat.h"
#include "diablo.h"
#include "engine.h"
#include "missiles.h"
#include "palette.h"
#include "scrollrt.h"

// effects

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "effects.h"
#include "appfat.h"
#include "engine.h"
#include "monster.h"
#include "msg.h"
#include "multi.h"
#include "player.h"
#include "sound.h"

// encrypt

#include "../types.h"
#include "../3rdParty/PKWare/pkware.h"
#include "encrypt.h"
#include "engine.h"

// engine

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "engine.h"
#include "appfat.h"
#include "diablo.h"
#include "dx.h"
#include "lighting.h"
#include "movie.h"
#include "palette.h"
#include "scrollrt.h"
#include "wave.h"

// error

#include "../types.h"
#include "error.h"
#include "control.h"
#include "dx.h"
#include "engine.h"
#include "scrollrt.h"
#include "stores.h"

// fault

#include "../types.h"
#include "fault.h"
#include "logging.h"

// gamemenu

#include "../types.h"
#include "gamemenu.h"
#include "cursor.h"
#include "diablo.h"
#include "effects.h"
#include "error.h"
#include "gendung.h"
#include "gmenu.h"
#include "init.h"
#include "interfac.h"
#include "loadsave.h"
#include "msg.h"
#include "multi.h"
#include "palette.h"
#include "pfile.h"
#include "player.h"
#include "scrollrt.h"
#include "sound.h"

//gendung

#include "../types.h"
#include "gendung.h"
#include "appfat.h"
#include "diablo.h"
#include "engine.h"
#include "lighting.h"

// gemnu

#include "../types.h"
#include "gmenu.h"
#include "control.h"
#include "diablo.h"
#include "dx.h"
#include "effects.h"
#include "engine.h"
#include "gendung.h"
#include "scrollrt.h"

// help

#include "../types.h"
#include "help.h"
#include "control.h"
#include "minitext.h"
#include "scrollrt.h"
#include "stores.h"

// init

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "../DiabloUI/diabloui.h"
#include "init.h"
#include "appfat.h"
#include "diablo.h"
#include "dx.h"
#include "effects.h"
#include "engine.h"
#include "missiles.h"
#include "multi.h"
#include "palette.h"
#include "pfile.h"
#include "sound.h"
#include "wave.h"

// interfac

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "interfac.h"
#include "appfat.h"
#include "diablo.h"
#include "dx.h"
#include "effects.h"
#include "engine.h"
#include "gendung.h"
#include "init.h"
#include "loadsave.h"
#include "monster.h"
#include "msg.h"
#include "multi.h"
#include "palette.h"
#include "pfile.h"
#include "player.h"
#include "plrmsg.h"
#include "portal.h"
#include "quests.h"
#include "scrollrt.h"

// inv

#include "../types.h"
#include "inv.h"
#include "control.h"
#include "cursor.h"
#include "diablo.h"
#include "dx.h"
#include "effects.h"
#include "engine.h"
#include "gendung.h"
#include "items.h"
#include "monster.h"
#include "msg.h"
#include "objects.h"
#include "player.h"
#include "plrmsg.h"
#include "quests.h"
#include "scrollrt.h"
#include "spells.h"
#include "stores.h"

// items

#include "../types.h"
#include "items.h"
#include "control.h"
#include "cursor.h"
#include "diablo.h"
#include "doom.h"
#include "dx.h"
#include "effects.h"
#include "engine.h"
#include "gendung.h"
#include "inv.h"
#include "lighting.h"
#include "missiles.h"
#include "monster.h"
#include "msg.h"
#include "multi.h"
#include "objects.h"
#include "player.h"
#include "quests.h"
#include "scrollrt.h"
#include "spells.h"
#include "stores.h"

// lighting

#include "../types.h"
#include "lighting.h"
#include "automap.h"
#include "diablo.h"
#include "engine.h"
#include "gendung.h"
#include "player.h"

// loadsave

#include "../types.h"
#include "loadsave.h"
#include "appfat.h"
#include "automap.h"
#include "codec.h"
#include "control.h"
#include "cursor.h"
#include "dead.h"
#include "diablo.h"
#include "doom.h"
#include "engine.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "lighting.h"
#include "missiles.h"
#include "monster.h"
#include "objects.h"
#include "palette.h"
#include "pfile.h"
#include "player.h"
#include "portal.h"
#include "quests.h"
#include "stores.h"

// logging

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "logging.h"

// mainmenu

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "../DiabloUI/diabloui.h"
#include "mainmenu.h"
#include "appfat.h"
#include "diablo.h"
#include "effects.h"
#include "gendung.h"
#include "init.h"
#include "movie.h"
#include "multi.h"
#include "pfile.h"
#include "player.h"
#include "sound.h"

// minitext

#include "../types.h"
#include "minitext.h"
#include "control.h"
#include "dx.h"
#include "effects.h"
#include "engine.h"
#include "quests.h"
#include "scrollrt.h"
#include "textdat.h"

// missiles

#include "../types.h"
#include "missiles.h"
#include "control.h"
#include "cursor.h"
#include "dead.h"
#include "diablo.h"
#include "effects.h"
#include "engine.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "lighting.h"
#include "monster.h"
#include "msg.h"
#include "multi.h"
#include "objects.h"
#include "player.h"
#include "spells.h"
#include "trigs.h"

// monster

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "monster.h"
#include "appfat.h"
#include "control.h"
#include "cursor.h"
#include "dead.h"
#include "debug.h"
#include "diablo.h"
#include "drlg_l4.h"
#include "effects.h"
#include "engine.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "lighting.h"
#include "minitext.h"
#include "missiles.h"
#include "movie.h"
#include "msg.h"
#include "multi.h"
#include "objects.h"
#include "path.h"
#include "player.h"
#include "quests.h"
#include "sound.h"
#include "textdat.h"
#include "themes.h"
#include "towners.h"
#include "trigs.h"

// movie

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "movie.h"
#include "diablo.h"
#include "effects.h"
#include "init.h"
#include "sound.h"

//mpqapi

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "mpqapi.h"
#include "appfat.h"
#include "encrypt.h"
#include "engine.h"
#include "multi.h"

//msg

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "../DiabloUI/diabloui.h"
#include "msg.h"
#include "appfat.h"
#include "automap.h"
#include "control.h"
#include "cursor.h"
#include "dead.h"
#include "diablo.h"
#include "dthread.h"
#include "encrypt.h"
#include "engine.h"
#include "gamemenu.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "lighting.h"
#include "missiles.h"
#include "monster.h"
#include "multi.h"
#include "nthread.h"
#include "objects.h"
#include "pfile.h"
#include "player.h"
#include "plrmsg.h"
#include "portal.h"
#include "quests.h"
#include "spells.h"
#include "sync.h"

//msgcmd

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "msgcmd.h"
#include "list.h"

// multi

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "../DiabloUI/diabloui.h"
#include "multi.h"
#include "appfat.h"
#include "diablo.h"
#include "dthread.h"
#include "engine.h"
#include "gendung.h"
#include "init.h"
#include "mainmenu.h"
#include "missiles.h"
#include "monster.h"
#include "msg.h"
#include "msgcmd.h"
#include "nthread.h"
#include "pack.h"
#include "pfile.h"
#include "player.h"
#include "plrmsg.h"
#include "portal.h"
#include "sync.h"
#include "tmsg.h"

// nthread

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "nthread.h"
#include "appfat.h"
#include "multi.h"

// objects

#include "../types.h"
#include "objects.h"
#include "automap.h"
#include "control.h"
#include "cursor.h"
#include "diablo.h"
#include "drlg_l4.h"
#include "effects.h"
#include "engine.h"
#include "error.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "lighting.h"
#include "minitext.h"
#include "missiles.h"
#include "monster.h"
#include "msg.h"
#include "multi.h"
#include "player.h"
#include "quests.h"
#include "setmaps.h"
#include "stores.h"
#include "themes.h"
#include "towners.h"
#include "track.h"

// pack

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "pack.h"
#include "engine.h"
#include "items.h"
#include "multi.h"
#include "player.h"
#include "stores.h"

// palette

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "palette.h"
#include "appfat.h"
#include "diablo.h"
#include "dx.h"
#include "engine.h"
#include "wave.h"

// path

#include "../types.h"
#include "path.h"
#include "gendung.h"

// pfile

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "../DiabloUI/diabloui.h"
#include "pfile.h"
#include "appfat.h"
#include "codec.h"
#include "diablo.h"
#include "engine.h"
#include "gendung.h"
#include "mainmenu.h"
#include "missiles.h"
#include "mpqapi.h"
#include "multi.h"
#include "pack.h"
#include "player.h"

// player

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "player.h"
#include "appfat.h"
#include "control.h"
#include "cursor.h"
#include "dead.h"
#include "diablo.h"
#include "effects.h"
#include "engine.h"
#include "gamemenu.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "lighting.h"
#include "minitext.h"
#include "missiles.h"
#include "monster.h"
#include "msg.h"
#include "multi.h"
#include "objects.h"
#include "path.h"
#include "portal.h"
#include "spells.h"
#include "stores.h"
#include "towners.h"
#include "wave.h"

// plrmsg

#include "../types.h"
#include "plrmsg.h"
#include "control.h"
#include "inv.h"
#include "player.h"
#include "quests.h"
#include "scrollrt.h"

// portal

#include "../types.h"
#include "portal.h"
#include "gendung.h"
#include "lighting.h"
#include "missiles.h"
#include "msg.h"
#include "player.h"

// quests

#include "../types.h"
#include "quests.h"
#include "control.h"
#include "cursor.h"
#include "diablo.h"
#include "effects.h"
#include "engine.h"
#include "gendung.h"
#include "items.h"
#include "minitext.h"
#include "missiles.h"
#include "monster.h"
#include "msg.h"
#include "multi.h"
#include "objects.h"
#include "palette.h"
#include "player.h"
#include "scrollrt.h"
#include "stores.h"
#include "towners.h"
#include "trigs.h"

// render

#include "../types.h"
#include "render.h"
#include "gendung.h"
#include "lighting.h"
#include "scrollrt.h"

#include "_asm.cpp"

// restrict

#include "../types.h"
#include "restrict.h"
#include "diablo.h"

// scrollrt

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "scrollrt.h"
#include "appfat.h"
#include "automap.h"
#include "control.h"
#include "cursor.h"
#include "dead.h"
#include "debug.h"
#include "diablo.h"
#include "doom.h"
#include "dx.h"
#include "engine.h"
#include "error.h"
#include "gendung.h"
#include "gmenu.h"
#include "help.h"
#include "init.h"
#include "inv.h"
#include "items.h"
#include "lighting.h"
#include "minitext.h"
#include "missiles.h"
#include "monster.h"
#include "multi.h"
#include "objects.h"
#include "palette.h"
#include "player.h"
#include "plrmsg.h"
#include "quests.h"
#include "town.h"
#include "render.h"

// setmaps

#include "../types.h"
#include "setmaps.h"
#include "appfat.h"
#include "drlg_l1.h"
#include "drlg_l2.h"
#include "drlg_l3.h"
#include "engine.h"
#include "gendung.h"
#include "objects.h"
#include "palette.h"
#include "quests.h"
#include "trigs.h"

// sha

#include "../types.h"
#include "sha.h"

// sound

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "sound.h"
#include "appfat.h"
#include "engine.h"
#include "wave.h"

// spells

#include "../types.h"
#include "spells.h"
#include "control.h"
#include "cursor.h"
#include "diablo.h"
#include "engine.h"
#include "gamemenu.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "missiles.h"
#include "monster.h"
#include "player.h"

// stores

#include "../types.h"
#include "stores.h"
#include "control.h"
#include "cursor.h"
#include "diablo.h"
#include "dx.h"
#include "effects.h"
#include "engine.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "minitext.h"
#include "multi.h"
#include "player.h"
#include "quests.h"
#include "scrollrt.h"
#include "spells.h"
#include "towners.h"

// sync

#include "../types.h"
#include "sync.h"
#include "appfat.h"
#include "engine.h"
#include "gendung.h"
#include "items.h"
#include "monster.h"
#include "msg.h"
#include "player.h"

// textdat

#include "../types.h"
#include "textdat.h"

// themes

#include "../types.h"
#include "themes.h"
#include "engine.h"
#include "gendung.h"
#include "items.h"
#include "monster.h"
#include "objects.h"
#include "quests.h"
#include "trigs.h"

// tmsg

#include "../types.h"
#include "tmsg.h"
#include "engine.h"

// town

#include "../types.h"
#include "town.h"
#include "automap.h"
#include "control.h"
#include "cursor.h"
#include "diablo.h"
#include "doom.h"
#include "dx.h"
#include "engine.h"
#include "error.h"
#include "gendung.h"
#include "gmenu.h"
#include "help.h"
#include "inv.h"
#include "items.h"
#include "minitext.h"
#include "multi.h"
#include "player.h"
#include "plrmsg.h"
#include "quests.h"
#include "scrollrt.h"
#include "stores.h"
#include "towners.h"
#include "trigs.h"
#include "render.h"

// towners

#include "../types.h"
#include "towners.h"
#include "cursor.h"
#include "effects.h"
#include "engine.h"
#include "gendung.h"
#include "inv.h"
#include "items.h"
#include "minitext.h"
#include "msg.h"
#include "multi.h"
#include "player.h"
#include "quests.h"
#include "stores.h"

// track

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "track.h"
#include "cursor.h"
#include "msg.h"
#include "player.h"

// trigs

#include "../types.h"
#include "trigs.h"
#include "appfat.h"
#include "control.h"
#include "cursor.h"
#include "diablo.h"
#include "effects.h"
#include "error.h"
#include "gendung.h"
#include "inv.h"
#include "msg.h"
#include "multi.h"
#include "player.h"
#include "quests.h"

// wave

#include "../types.h"
#include "../3rdParty/Storm/Source/storm.h"
#include "wave.h"
#include "appfat.h"
#include "engine.h"
#include "init.h"

